### ISSUE TITLE
Hero Text Gradient Missing

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/StarDustAdventures#1]
### Images (For reference) :
![image](https://github.com/user-attachments/assets/e8c7298f-2352-4766-af2c-d9690b8d907a)

### Possible Fixes : 
- Use of `background-clip` property in CSS

**Comment by ArjunQBTech** [comment]
@MohitQuadB kindly complete this by today

**Comment by MohitQuadB** [comment]
![image](https://github.com/user-attachments/assets/3c0babf0-834b-4ae4-a675-0b45a129da2f)
I have implemeneted the changes required using background-clip ,have a look @ArjunQBTech

**Comment by MohitQuadB** [comment]
![image](https://github.com/user-attachments/assets/4bc6d456-0203-48d2-badd-1667622143c7)
This has been implemented ,pls have a look @ArjunQBTech

**Comment by ArjunQBTech** [comment]
Great! You can do a PR now, and I will review it within today and suggest any necessary changes if applicable
