### ISSUE TITLE
Importing Public Assets in JS

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/StarDustAdventures#50]
### Description : 
Public Assets are being imported in JS in `src\game_frontend\src\pages\Dashboard\Airdrop\index.tsx` in line number 5

### Logs :
```bash
Assets in public directory cannot be imported from JavaScript.
If you intend to import that asset, put the file in the src directory, and use /src/assets/images/astronaut.webp instead of /public/assets/images/astronaut.webp.
```

![image](https://github.com/user-attachments/assets/59b5031e-4374-4637-bab7-3d218f661f3f)

**Comment by shadabkhan16** [comment]
Add Lazy Loading to Image

**Comment by ArjunQBTech** [comment]
This issue has been closed
