### ISSUE TITLE
rounded border at corners in the Sidebar

### ISSUE THREAD

**Issue by poornima005** [ICP-hub/StarDustAdventures#57]
The sidebar must have rounded borders at the corners. The rounded corners should be applied to both the top and bottom edges .
![Screenshot (72)](https://github.com/user-attachments/assets/8cd7e0a5-043d-4d91-bd11-68dd75a0593f)
![Screenshot (73)](https://github.com/user-attachments/assets/3ea637ac-5816-4fef-8ee8-1b68e130d4b8)

**Comment by shadabkhan16** [comment]
Issue fixed 
<img width="1434" alt="Screenshot 2024-12-10 at 12 54 11 PM" src="https://github.com/user-attachments/assets/499ac651-ce99-41d5-9326-c35a75cc5db7">
