### ISSUE TITLE
Alignment of Tags Not Centered

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/StarDustAdventures#59]
### Description : 
Alignment of Tags Not Centered
![image](https://github.com/user-attachments/assets/b1740b21-c657-4607-a0db-d124bd923ea5)

**Comment by shadabkhan16** [comment]
Align tags in the center
<img width="1425" alt="Screenshot 2024-12-10 at 11 48 31 AM" src="https://github.com/user-attachments/assets/8ef1d088-1dcc-45df-bc37-9372d94e4d26">
