### ISSUE TITLE
Typo: Incorrect Component Name InfoTootip should be InfoToolTip

### ISSUE THREAD

**Issue by shadabkhan16** [ICP-hub/StarDustAdventures#64]
# Issue Description
The component is incorrectly named as InfoTootip instead of InfoToolTip.

## Navigation
File :``` src/game_frontend/src/components/dashboard/airdrop/Incentives/index.tsx ```
 Line to Change : 
 ```import InfoToolTip from '../../../ui/InfoToolTip/InfoTooltip'```

**Comment by ArjunQBTech** [comment]
I have fixed this. Will soon push the fix
