### ISSUE TITLE
Issue : onKeyDown Escape Button, Modal Closes and doesn't open again

### ISSUE THREAD

**Issue by ArjunQBTech** [ICP-hub/StarDustAdventures#66]
## Steps to reproduce : 
1. Go to Landing Page of Game
2. Click on **Connect Wallet**
3. Press `Esc` to close the Modal
4. Try Opening the Modal

## Possible Fix : 
- This is an issue related to HTML Dialog Elements. Will have to go through the docs to understand the Events fired on `Esc` Keydown

**Comment by shadabkhan16** [comment]
The bug is fixed.
![ScreenRecording2024-12-11at5 05 07PM-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/7a1d944c-f6fc-46a7-b8e9-3e7e85245c3a)
